source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'pg'
gem 'pry-rails'

gem 'postamt', path: '..'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
