source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', git: 'https://github.com/rails/rails.git', branch: '4-0-stable'
gem 'pg'
gem 'pry-rails'

gem 'postamt', path: '..'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', group: :development

# To use debugger
# gem 'debugger'
