source 'https://rubygems.org'

gem 'rails', github: 'rails/rails', branch: '4-1-0'
gem 'pg'
gem 'pry-rails'

gem 'postamt', path: '..'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', group: :development

# To use debugger
# gem 'debugger'
