source 'https://rubygems.org'

gem 'rails', '4.2.0.beta1'
gem 'pg'
gem 'pry-rails'

gem 'postamt', path: '..'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', group: :development

# To use debugger
# gem 'debugger'
